<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\CategoriesManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/ProductManager.php';
include_once $this->targetDirs[3].'/src/Service/CategoriesManager.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php'));

return $this->privates['App\Service\CategoriesManager'] = new \App\Service\CategoriesManager($a, new \App\Service\ProductManager($a));
