<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\MenuManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/MenuManager.php';

return $this->privates['App\Service\MenuManager'] = new \App\Service\MenuManager(($this->privates['App\Service\CategoriesManager'] ?? $this->load(__DIR__.'/getCategoriesManagerService.php')));
