<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.FIs6xeg' shared service.

return $this->privates['service_locator.FIs6xeg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('menuManager' => function (): ?\App\Service\MenuManager {
    return ($this->privates['App\Service\MenuManager'] ?? $this->load(__DIR__.'/getMenuManagerService.php'));
}));
